import type { Metadata } from "next";
import "./styles/globals.css";
import { Header } from "@components/Header";
import Skills from "@components/Skills";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background overflow-x-hidden">
        <div className="all-content">
          <Header />
          <div className="absolute inset-0 flex items-center z-0 ml-20">
            <div className={`rounded-full bg-blue-600 mix-blend-multiply filter blur-2xl opacity-10 w-[50%] h-[75%] zoom-in-out`}></div>
          </div>
          {children}
        </div>
          <Skills />
      </body>
    </html>
  );
}
